version: "3"
services:
  numtrack-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8302:8302"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
  numtrack-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - numtrack-backend
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    ports:
        - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
